server:
  port: 8080

##????
logging:
  level:
    root: INFO

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  profiles.active: local
  # ??? ?? ??
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://kmw0628.duckdns.org:15430/foodest?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: foodest
    password: foodest
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true
  # JPA ??
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true # 개발 시 SQL을 보고 싶다면 true로 설정
        format_sql: true # SQL 포맷팅이 필요하다면 true로 설정
